### ISSUE TITLE
Implement VT private API

### ISSUE THREAD

**Issue by Genbox** [Genbox/VirusTotalNet#18]
Support the private VirusTotal API as documented at https://www.virustotal.com/en/documentation/private-api/

Note that the endpoints are the same, but the API methods are different. The private API methods can only be called with a private API key, which have no rate limiting due to the fact that you pay for an amount of requests instead. Some methods are only available with the unlimited API key tier.

Required features:
1. Fullly mapped API functions for private API
2. Ability to determine what kind of API key is provided, and ignore limits when an unlimited key is set.

Nice to have features:
1. Provide a large list of files, the high-level API take care of batching/rate limits (see #16)
2. High-level API should take care of getting reports and upload files
3. When providing files, save file name, hash and scan request id locally and cross reference them with scan results. This makes it easier to correlate results.
4. Only send unique resources to VT. Use eager queue such that if a batch of 100 files is sent, but 20 are duplicates, fetch more from the source until we have 100 files again or the source is empty. Use correlation from (3) when returning results to the user.
5. Provide async interface (see #15) and make library thread safe.
6. Provide in-memory caching for already queried results. Provide configurable cache/expunge strategies as well as configurable cache sizes.
7. Provide file extension/file size filters in high-level APIs
8. Make a filter that only uploads files with valid PE headers

**Comment by keithjjones** [comment]
Note - I have use of a private API key that is unlimited (and therefore unlocks all functionality).  I can help here, or at least test the extra functionality.

"Ability to determine what kind of API key is provided, and ignore limits when an unlimited key is set."  are there limits imposed by this library?  I did not see limiting in the code.

**Comment by Genbox** [comment]
Currently there is no rate limiting implemented in the library. If it becomes part of the library, there is no reason to activate it (or at least warn the user) when an unlimited key is used.

**Comment by keithjjones** [comment]
Awesome.  There are definitely some things I see in this API I want to implement, like downloading samples.  If I have time this week I'll take a stab at some of it.

**Comment by keithjjones** [comment]
Do you have any ideas how to determine this? "2. Ability to determine what kind of API key is provided, and ignore limits when an unlimited key is set."  

I've been trying to knock off some of the private API this week.  I haven't hit everything on your list, but I think there is a good start.

**Comment by leechristensen** [comment]
@Genbox what's the status on accepting this pull? Anything blocking? I can help test you need help.
