### ISSUE TITLE
VirusTotal API V3 is out. 

### ISSUE THREAD

**Issue by HavermansStef** [Genbox/VirusTotalNet#46]
https://developers.virustotal.com/v3.0/reference

Todo: 
Make the migration to the V3 API.

**Comment by Genbox** [comment]
Thanks for the heads up.

**Comment by Jon2G** [comment]
Hi, I just made some changes in order to support API V3 while preserving API V2.
I'm pretty new to VirusTotal so any help is welcome, also tell me if you want me to make a pull request.

**Comment by Genbox** [comment]
Hi Jon2G,

VirusTotal has (for the 5th time over 10 years) declined my proposal for working together in exchange for an API key for testing. They do not want to support this project, nor do they want to have a conversation about how to go forward with the project, unless I pay them a very large sum of money.

I will therefore not be extending this project with support for V3 or any other new features they provide. It will regularly be maintained to ensure that it works for all existing implementers.

Sorry for the inconvenience, but VirusTotal has always been a complete brick wall to talk with and I don't want to expend the effort anymore.
