### ISSUE TITLE
SendFileAsync leads to ObjectDisposedException

### ISSUE THREAD

**Issue by monnster** [Genbox/VirusTotalNet#50]
Situation is described here - https://stackoverflow.com/questions/71017928/cannot-access-a-disposed-object-object-name-system-net-http-multipartformdata

Solution is simple: make this method async and add await at the end:

public **async** Task<ScanResult> ScanFileAsync(Stream stream, string filename)
{
  // ...
  return **await** GetResponse<ScanResult>("file/scan", HttpMethod.Post, multi);
}

**Comment by Genbox** [comment]
You are absolutely right. Good old async bites again. Thanks for reporting.
